export const GET_USERS_RESPONSE = 'GET_USERS_RESPONSE';
export const GET_USER_RESPONSE = 'GET_USER_RESPONSE';
export const ADD_NEW_USER_RESPONSE = 'ADD_NEW_USER_RESPONSE';
export const UPDATE_EXISTING_USER_RESPONSE = 'UPDATE_EXISTING_USER_RESPONSE';
export const DELETE_USER_RESPONSE = 'DELETE_USER_RESPONSE';

export const GET_GROUPS_RESPONSE = 'GET_GROUPS_RESPONSE';

export const API_CALL_BEGIN = 'API_CALL_BEGIN';
export const API_CALL_ERROR = 'API_CALL_ERROR';
